### ISSUE TITLE
Format Selection is formatting the entire file

### ISSUE THREAD

**Issue by lsouder-ozone3d** [EeyoreLee/vscode-extension-yapf#101]
I am having an issue where doing `Format Selection` is making changes outside the selected range. To clarify, doing `Format Document` does yield different results (more changes), so they _are_ at least different.

I am using:
- yapf 0.40.2
- yapf VSCode extension version v2023.11.122090301
- Python 3.9.13

My .vscode/settings.json is
```json
{
    "python.languageServer": "Pylance",
    "python.analysis.diagnosticSeverityOverrides": {

    },
    "python.analysis.inlayHints.variableTypes": "off",
    "python.analysis.inlayHints.functionReturnTypes": true,
    "python.analysis.inlayHints.callArgumentNames": "off",
    "[python]": {
        "editor.defaultFormatter": "eeyore.yapf"
    },
}
```

**Comment by EeyoreLee** [comment]
@lsouder-ozone3d - hi, has the formatOnSave affected you? Could you try the following setting for `[python]` section
```
  "[python]": {
    "editor.formatOnSave": false,
    "editor.defaultFormatter": "eeyore.yapf",
    "editor.formatOnType": false
  }
```
If there's still a unexpect problem, please show me a code snippet can reproduct this as I just try this on my side that seems working fine.

**Comment by lsouder-ozone3d** [comment]
@EeyoreLee thanks for responding. That config didn't solve the problem.

```python
def do_something():
    xs = []
    for x in xs:
        y = 'y'
        
        if y:
            pass

def do_something_else():
    return '-path 1'
```

Line 5 has 2 unnecessary tabs. If I `Format Selection` for just the last line, it will strip the whitespace in Line 5

**Comment by EeyoreLee** [comment]
@lsouder-ozone3d - yup, I reproducted it not only through vscode extension but also `yapf xx.py -l 10-10 -i`. So it's a bug of yapf package. I'll issue it to yapf repo.

**Comment by EeyoreLee** [comment]
Seems there's a PR to fix it, upgrade your local yapf package when yapf merge it may fix it. Related PR [yapf #1102](https://github.com/google/yapf/pull/1102)

**Comment by lsouder-ozone3d** [comment]
@EeyoreLee Thanks for looking into that! I'll close out this issue and watch for a change over there.
