### ISSUE TITLE
extension crash after installation

### ISSUE THREAD

**Issue by hoho51** [EeyoreLee/vscode-extension-yapf#14]
there is error in output

`2023-08-25 11:48:26.165 [info]     import attrs
  File "c:\xxx\xxx\\.vscode\extensions\eeyore.yapf-0.1.6\bundled\libs\attrs\__init__.py", line 62, in <module>

2023-08-25 11:48:26.168 [info]     __getattr__ = _make_getattr(__name__)

2023-08-25 11:48:26.168 [info] NameError: name '_make_getattr' is not defined`

**Comment by EeyoreLee** [comment]
hi @hoho51 - Could you tell me how do you install this extension ? from microsoft marketplace or Vscode Extensions. And what did you do next. I just check the code, `_make_getattr` was defined but in line 65.

**Comment by EeyoreLee** [comment]
Could you show the version of python you used ?  Can you also confirm the output by using this python and run `python c:\\xxx\\xxx\\.vscode\\extensions\\eeyore.yapf-0.1.6\\bundled\tool\\lsp_server.py`

**Comment by hoho51** [comment]
> hi @hoho51 - Could you tell me how do you install this extension ? from microsoft marketplace or Vscode Extensions. And what did you do next. I just check the code, `_make_getattr` was defined but in line 65.

Sorry, I forgot that I had changed the extension's code earlier, resulting in an error message that may be troubling to you, the error initially reported was
`File "/home/xxx//.vscode-server/extensions/eeyore.yapf-0.1.6/bundled/libs/attrs/__init__.py", line 3, in <module
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/home/xxx/anaconda3/lib/python3.8/site-packages/attr/__init__.py)
`

**Comment by hoho51** [comment]
> Could you show the version of python you used ? Can you also confirm the output by using this python and run `python c:\\xxx\\xxx\\.vscode\\extensions\\eeyore.yapf-0.1.6\\bundled\tool\\lsp_server.py`

I'm using python 3.8, and will also be using 3.9.6, and neither version will launch the extension. I tried to run it with the command you provided and the program hangs without showing any message

**Comment by EeyoreLee** [comment]
> > Could you show the version of python you used ? Can you also confirm the output by using this python and run `python c:\\xxx\\xxx\\.vscode\\extensions\\eeyore.yapf-0.1.6\\bundled\tool\\lsp_server.py`
> 
> I'm using python 3.8 and 3.9.6, and neither version will launch the extension. I tried to run it with the command you provided and the program hangs without showing any message

Thanks for the detail. @hoho51 - If there is no any error raised, it means that the server is runing fine. Can you try to delete the dictionary `/home/xxx//.vscode-server/extensions/eeyore.yapf-0.1.6` and uninstall this extension from built-in Vscode Extensions. the `AttrsInstance` is defined in `attr.__init__.py` in line 34 like the following 
```
class AttrsInstance:
    pass


__all__ = [
    "Attribute",
    "AttrsInstance",
```
I just tested it in python3.8, python3.9, python3.11 and python3.6 in Windows. every version is worked but python3.6 cause the LSP don't support it.

**Comment by hoho51** [comment]
> > > Could you show the version of python you used ? Can you also confirm the output by using this python and run `python c:\\xxx\\xxx\\.vscode\\extensions\\eeyore.yapf-0.1.6\\bundled\tool\\lsp_server.py`
> > 
> > 
> > I'm using python 3.8 and 3.9.6, and neither version will launch the extension. I tried to run it with the command you provided and the program hangs without showing any message
> 
> Thanks for the detail. @hoho51 - If there is no any error raised, it means that the server is running fine. Can you try to delete the dictionary `/home/xxx//.vscode-server/extensions/eeyore.yapf-0.1.6` and reinstall this extension from built-in Vscode Extensions. the `AttrsInstance` is defined in `attr.__init__.py` in line 34 like the following
> 
> ```
> class AttrsInstance:
>     pass
> 
> 
> __all__ = [
>     "Attribute",
>     "AttrsInstance",
> ```
> 
> I just tested it in python3.8, python3.9, python3.11 and python3.6 in Windows. every version is worked but python3.6 cause the LSP don't support it.

Reinstalling doesn't work.

No error was raised. It looks like the extension is using my environment's python libs, but the version of my environment's libs doesn't match the version of the libs used by the extension, so some objects can't be imported, can the extension be set to prioritize the use of the libs that come with the extension instead of the libs that are in my environment variables?

**Comment by EeyoreLee** [comment]
@hoho51 - edit the settings like the following will do that
```
{
    "[python]": {
        "editor.formatOnSaveMode": "file",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "eeyore.yapf"
    },
    "yapf.importStrategy": "useBundled"
}
```

**Comment by hoho51** [comment]
> 
it works! thank you for your support.

**Comment by EeyoreLee** [comment]
Thanks for your all clarifying. I found out another problem that I install the lastest version yapf in bundled. I will remove it in next release.

**Comment by EeyoreLee** [comment]
@hoho51 - I release a new version v0.1.7 by optimizing import order. the pygls and other libs required by server will be first place, and if you setup `importStrategy` to `fromEnvironment`, the `yapf` package you installed will be front of `yapf` bundled, else setup`useBundled` will be use bundled `yapf` rather than you installed.   
In short, both of knobs will be work for your situation.
