### ISSUE TITLE
Path to .style.yapf

### ISSUE THREAD

**Issue by j-krl** [EeyoreLee/vscode-extension-yapf#43]
I need to be able to set the path to my `.style.yapf` file as I am using a monorepo and it is not in the workspace root. Is this possible?

**Comment by EeyoreLee** [comment]
@j-krl - hi, all the yapf native args can be set through `yapf.args`. So you can edit your vscode settings to
```
"yapf.args": ["--style", "{your style file path}"]
```

**Comment by j-krl** [comment]
Hmm, I'd rather not have to use custom VS Code settings. Back when VS Code handled it natively it just auto-discovered my `.style.yapf` file.

**Comment by EeyoreLee** [comment]
@j-krl - well, I just took a look at the yapf source code. yep, it will auto find the style file on the cwd and its parent directories which is also your monorepo root directory xD.

**Comment by j-krl** [comment]
Yeah, but my .style.yapf file is in a child directory because not all the children are Python repos. Honestly it's not a big deal though, it's a minimal amount of extra config. Thanks for the quick response!
