### ISSUE TITLE
Yapf formatter with devcontainers not sticking

### ISSUE THREAD

**Issue by alexanderluiscampino** [EeyoreLee/vscode-extension-yapf#44]
My yapf formatter is just not sticking. It keeps asking me that there are multiple default formatters. I'm on devcontainer. There aren't multiple formatter, just yapf. What is going on? for the record I'm doing ctrl+s to save the file before having to resort to the Format Document in the command pallete. 

![yapf](https://github.com/EeyoreLee/vscode-extension-yapf/assets/32500355/2414242c-e409-45ef-8d10-36902957567a)

These used to work before, I just changed to latest version of devcontainers definitions according to [this](https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions)

These are my vscode devcontainer settings:
```json
"settings": {
				"python.defaultInterpreterPath": "/usr/local/bin/python",
				"python.testing.pytestPath": "/usr/local/py-utils/bin/pytest",
				"python.languageServer": "Pylance",
				"python.analysis.typeCheckingMode": "basic",
				"python.analysis.completeFunctionParens": true,
				"python.autoComplete.addBrackets": true,
				"autoDocstring.startOnNewLine": true,
				// The character to replace whitespace in new branch names.
				"git.branchWhitespaceChar": "-",
				"git.pruneOnFetch": true,
				"git.autofetch": true,
				"git.enableSmartCommit": true,
				"git.confirmSync": false,
				"gitlens.gitCommands.skipConfirmations": [
					"fetch:command",
					"stash-push:command",
					"switch:command",
					"branch-create:command"
				],
				"gitlens.views.repositories.files.layout": "tree",
				"prettier.printWidth": 120,
				"prettier.tabWidth": 4,
				"editor.minimap.enabled": false,
				"editor.renderControlCharacters": true,
				"editor.renderWhitespace": "all",
				"editor.formatOnPaste": true,
				"editor.formatOnSave": true,
				"editor.formatOnType": true,
				"files.insertFinalNewline": true,
				"editor.codeActionsOnSave": {
					"source.organizeImports": true
				},

				"[yaml]": {
					"editor.defaultFormatter": "esbenp.prettier-vscode",
					"editor.formatOnSave": true
				},
				"[json]": {
					"editor.defaultFormatter": "esbenp.prettier-vscode",
					"editor.formatOnSave": true
				},
				"[jsonc]": {
					"editor.defaultFormatter": "esbenp.prettier-vscode",
					"editor.formatOnSave": true
				},
				"[python]": {
					"editor.formatOnSaveMode": "file",
					"editor.formatOnSave": true,
					"editor.defaultFormatter": "eeyore.yapf"
				}
			}
```

I'd like to point out same does not happen outside the devcontainer. On my host it works fine.

**Comment by EeyoreLee** [comment]
Can you try the pined issue with tag question to set the python extension default formatter to none.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alexandre Campino ***@***.***>
Sent: Saturday, September 30, 2023 6:11:36 AM
To: EeyoreLee/vscode-extension-yapf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EeyoreLee/vscode-extension-yapf] Yapf formatter with devcontainers not sticking (Issue #44)


My yapf formatter is just not sticking. It keeps asking me that there are multiple default formatters. I'm on devcontainer. There aren't multiple formatter, just yapf. What is going on?

[yapf]<https://user-images.githubusercontent.com/32500355/271728664-2414242c-e409-45ef-8d10-36902957567a.gif>

These used to work before, I just changed to latest version of devcontainers definitions according to this<https://github.com/microsoft/vscode-python/wiki/Migration-to-Python-Tools-Extensions>

These are my vscode devcontainer settings:

"settings": {
                                "python.defaultInterpreterPath": "/usr/local/bin/python",
                                "python.testing.pytestPath": "/usr/local/py-utils/bin/pytest",
                                "python.languageServer": "Pylance",
                                "python.analysis.typeCheckingMode": "basic",
                                "python.analysis.completeFunctionParens": true,
                                "python.autoComplete.addBrackets": true,
                                "autoDocstring.startOnNewLine": true,
                                // The character to replace whitespace in new branch names.
                                "git.branchWhitespaceChar": "-",
                                "git.pruneOnFetch": true,
                                "git.autofetch": true,
                                "git.enableSmartCommit": true,
                                "git.confirmSync": false,
                                "gitlens.gitCommands.skipConfirmations": [
                                        "fetch:command",
                                        "stash-push:command",
                                        "switch:command",
                                        "branch-create:command"
                                ],
                                "gitlens.views.repositories.files.layout": "tree",
                                "prettier.printWidth": 120,
                                "prettier.tabWidth": 4,
                                "editor.minimap.enabled": false,
                                "editor.renderControlCharacters": true,
                                "editor.renderWhitespace": "all",
                                "editor.formatOnPaste": true,
                                "editor.formatOnSave": true,
                                "editor.formatOnType": true,
                                "files.insertFinalNewline": true,
                                "editor.codeActionsOnSave": {
                                        "source.organizeImports": true
                                },

                                "[yaml]": {
                                        "editor.defaultFormatter": "esbenp.prettier-vscode",
                                        "editor.formatOnSave": true
                                },
                                "[json]": {
                                        "editor.defaultFormatter": "esbenp.prettier-vscode",
                                        "editor.formatOnSave": true
                                },
                                "[jsonc]": {
                                        "editor.defaultFormatter": "esbenp.prettier-vscode",
                                        "editor.formatOnSave": true
                                },
                                "[python]": {
                                        "editor.formatOnSaveMode": "file",
                                        "editor.formatOnSave": true,
                                        "editor.defaultFormatter": "eeyore.yapf"
                                }
                        }

**Comment by alexanderluiscampino** [comment]
Hi @EeyoreLee , thanks for the reply. 

Same outcome:

![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/32500355/cd0820e3-73d5-4d8b-a09c-f6e8f06798b7)

Also, this won't be a supported option soon. That's why I installed the yapf formatter extension in the first place, since I started getting the devcontainer warnings for incorrect settings soon to be deprecated.

![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/32500355/c6239df2-923a-4c51-97f2-b19c63229543)

Furthermore, if I force it to use YAPF I start getting a command line error (debug console) and doesn't do anything..

![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/32500355/72de6497-d353-4199-93f5-3eba3c994626)

**Comment by EeyoreLee** [comment]
@alexanderluiscampino - hi, sorry for the late reply. I just came back from traveling. I first elaborate the reason why set the `python.formatting.provider` to `none`. Vscode is going to use LSP, a new framework for extension, that separates front and backend so that we can use others program language. This is also the reason why formatter will be deprecated. But for now, the lastest version Vscode still use the old framework, so set it to `none` will avoid some conflicts. related issue [microsoft/vscode-python#21870](https://github.com/microsoft/vscode-python/issues/21870).
Back, the vscode show there's two formatter `ms-python` and `yapf`, and I find out there's a wave line at the `eeyore.yapf`, could you show what hint here.  And could you push a minimal image can reproduct the issue to dockerhub, then I can reproduct on my side.
