### ISSUE TITLE
Python 3.7 is not supported

### ISSUE THREAD

**Issue by dtczest** [EeyoreLee/vscode-extension-yapf#53]
Python 3.7 is not supported, I think due to the version of typing_extensions in use? This should either be supported or a minimum python version should be documented on the extension. Thanks!

**Comment by EeyoreLee** [comment]
@dtczest - Thanks for your issue. I think here's a bug that I need downgrade pygls package as I tested python3.7 in PR actions but just formatting flow without server. I'll fix it later to support python3.7 and the minimum version should be 3.7.

**Comment by EeyoreLee** [comment]
@dtczest - I just took a look for [python guide](https://devguide.python.org/versions/). Python 3.7 is EOL, so I will align this. Sorry for dropping support for python3.7. I'll document it on extension.

**Comment by dtczest** [comment]
Got it, thank you!
