### ISSUE TITLE
The "yapf" extension is configured to format programs, but not "Python"-files.

### ISSUE THREAD

**Issue by Zacharia2** [EeyoreLee/vscode-extension-yapf#61]
my settings.json:

```json
    "[python]": {
        "editor.formatOnSaveMode": "file",
        "editor.formatOnSave": true,
        "editor.defaultFormatter": "eeyore.yapf"
    },
    "yapf.args": [
        "--style",
        "{based_on_style: pep8, indent_width: 2}"
    ],
```

**Comment by Zacharia2** [comment]
This is a strange problem, I don't know what's happening, it's not working.


版本: 1.83.1 (user setup)
提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc
日期: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by EeyoreLee** [comment]
@Zacharia2 - Do you mean `yapf` can format other program languages? But it not work for `.py` file ? Can you show some output of the `yapf`.

**Comment by Zacharia2** [comment]
I'm using vscode, I have yapf installed and configured as per the instructions for formatting .py files.

I created a test.py file, which I opened with vscode and then right clicked and chose to format the document.

Then vscode prompted me with this message, "The "yapf" extension is configured to format programs, but not "Python"-files."

**Comment by EeyoreLee** [comment]
@Zacharia2 - hi, I switch the version of vscode to 1.83.1 and reproduct it. It seems cause you click the knob when yapf extension is starting. It works when the right click menu turn to the following
![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/49790022/30934cff-f814-420f-8ca2-3aec5205bc5f)
Or when this message appears in the output
![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/49790022/5285457e-dc49-47d2-99bf-658190f5fb4b)
Can you try it again, or show me the output of yapf  channel

**Comment by Zacharia2** [comment]
For vscode, probably the Python Environment Manager plugin will manage the python environment better. Using this plugin to quickly switch to the right python environment can solve this problem.
