### ISSUE TITLE
Formatter is constantly formatting

### ISSUE THREAD

**Issue by danielschenk** [EeyoreLee/vscode-extension-yapf#76]
The formatter formats instantly when editing my file. This makes it impossible to do certain edits (eg. adding a newline between two function params, to insert another param) because it gets reverted instantly. This is very annoying, the formatter should format on save only (if this is enabled of course).

**Comment by xsjad0** [comment]
setting ```editor.formatOnType``` to ```false``` deactivates this behaviour

![grafik](https://github.com/EeyoreLee/vscode-extension-yapf/assets/34922647/2e5af4aa-6a1b-40ee-80ef-9ef57497bec6)

**Comment by EeyoreLee** [comment]
@xsjad0 - Thanks, that's right. @danielschenk - edit settings as xsjad0 said will address it. I'll add a note in extension homepage for this later.

**Comment by danielschenk** [comment]
I never had this behavior before, it started when I installed this extension. When I looked it up in the settings UI, I noticed this:

![image](https://github.com/EeyoreLee/vscode-extension-yapf/assets/9695838/94c593f5-9263-48cd-a578-557e3321c677)

Resetting the setting from the UI didn't help. The setting is not in our team's settings.json (which lives in the repo), and I want to keep it that way because it should be a user preference. I had to add it manually to my user settings.json. From that moment the comment changed to "Also modified elsewhere". Could it be that the extension somehow influences it?

**Comment by EeyoreLee** [comment]
@danielschenk - this extension hasn't modified this setting. You can find out by hovering the mouse over the hint `User[Python] Editor: Format On Type` by searching `@id:editor.formatOnType @lang:python format on type`. Then there's a hint `Default value changed` and hover over it again. It said `Default setting value overridden by Pylance`, so I think the the extension that somehow influences the setting is `Pylance` not `yapf`.

**Comment by EeyoreLee** [comment]
@danielschenk - The new prerelease version won't format the ast node if the last line is empty or endwith `,`, maybe helpful for you. But set the `formatOnType` to false is better for your situation. The default true cause the Pylance and I don't plan to add a new knob setting to config whether turn on/off format on type by default false as someone who wanna this feature need to set two settings.
