### ISSUE TITLE
Yapf formatting on type instead of on save

### ISSUE THREAD

**Issue by tomascsantos** [EeyoreLee/vscode-extension-yapf#83]
I have this installed and this is my settings.json:

<img width="721" alt="image" src="https://github.com/EeyoreLee/vscode-extension-yapf/assets/7690514/8429999f-9578-4d32-bd3c-3ffe879de19f">

When I type, formatting will start correcting my changes in a VERY annoying way. I love auto-format on save, but I would like to disable format on type, could you help me debug this? From my yaml I wouldn't expect this to be happening. Thank you!

**Comment by lroling8350** [comment]
Running into a similar issue. It's not every key typed but instead everytime I hit enter if fires the formatter

**Comment by lroling8350** [comment]
Was able to fix this by adding `"editor.formatOnType": false` to the python section like so 
```
"[python]": {
    "editor.formatOnType": false,
```

**Comment by tomascsantos** [comment]
You are a scholar and a saint, thank you so much for that workaround

**Comment by EeyoreLee** [comment]
@lroling8350 @tomascsantos - hi, I noticed some users didn't need the feature `formatOnType`, also for me. The default value of `formatOnType` was overrided by `Pylance` to change to true cause it need the feature to do somethings. Do you thought if I add a new knob that turn-off this feature by default like `yapf.formatOnType` will be better ?  But for some users need this feature will set both setting `yapf.formatOnType` and `editor.formatOnType` to true.
