### ISSUE TITLE
Keep getting the message "there is no formatter for 'python' files installed"

### ISSUE THREAD

**Issue by janwijbrand** [EeyoreLee/vscode-extension-yapf#84]
Hi, I'm trying to get this extension to work. I've added the following lines to my `settings.json`:

```
"python.formatting.provider": "none",
"[python]": {
  "editor.wordBasedSuggestions": false,
  "editor.defaultFormatter": "eeyore.yapf"
}
```

But whenever I try to use the "format document" command, VSCode shows a dialog "There is no formatter for 'Python' files installed". Interestingly, VSCode tries to help with configuration suggestions when one is editing `settings.json`. There's no suggestion inside a `"[python]"` section though for `"editor.defaultFormatter"`, where it does suggest this configuration key in, for example, in an `"[xml]"` section. See screenshots.

VSCode version `1.84.2`. eeyore.yapf version `0.1.10`.

Editor suggestions for an `"[xml]"` section:

<img width="693" alt="autosuggest-default-formatter-1" src="https://github.com/EeyoreLee/vscode-extension-yapf/assets/530800/afb0cbbb-7bf2-4e46-893a-a49dbc489eff">

Editor suggestions for an `"[python]"` section:

<img width="731" alt="autosuggest-default-formatter-2" src="https://github.com/EeyoreLee/vscode-extension-yapf/assets/530800/64442873-98d4-4144-8193-ea82c5b1ec04">

**Comment by janwijbrand** [comment]
Quick followup: after installing the autopep8 extension the `"editor.defaultFormatter"` _is_ suggested. As if "eeyore.yapf" is not recognized by VSCode as a valid formatter.

**Comment by EeyoreLee** [comment]
> Hi, I'm trying to get this extension to work. I've added the following lines to my `settings.json`:
> 
> ```
> "python.formatting.provider": "none",
> "[python]": {
>   "editor.wordBasedSuggestions": false,
>   "editor.defaultFormatter": "eeyore.yapf"
> }
> ```
> 
> But whenever I try to use the "format document" command, VSCode shows a dialog "There is no formatter for 'Python' files installed". Interestingly, VSCode tries to help with configuration suggestions when one is editing `settings.json`. There's no suggestion inside a `"[python]"` section though for `"editor.defaultFormatter"`, where it does suggest this configuration key in, for example, in an `"[xml]"` section. See screenshots.
> 
> VSCode version `1.84.2`. eeyore.yapf version `0.1.10`.
> 
> Editor suggestions for an `"[xml]"` section:
> 
> <img alt="autosuggest-default-formatter-1" width="693" src="https://user-images.githubusercontent.com/530800/283084276-afb0cbbb-7bf2-4e46-893a-a49dbc489eff.png">
> Editor suggestions for an `"[python]"` section:
> 
> <img alt="autosuggest-default-formatter-2" width="731" src="https://user-images.githubusercontent.com/530800/283084326-64442873-98d4-4144-8193-ea82c5b1ec04.png">

@janwijbrand - maybe cause the wave line `"editor.defaultFormatter"` is already exist. this property has nothing to do with formatter extension. the value of `"editor.defaultFormatter"` is indeed registered by formatter extension. And the crash maybe cause the wrong python interpreter. Could you try to select a python interpreter that python3.8 or greater by ms-python extension.

**Comment by janwijbrand** [comment]
Thanks for you reply. And you are probably correct: the python that is picked up from the VSCode environment cannot start the bundled lsp code. The error output of the extension pointed me there now. I understand why now.
